apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-worker
  template:
    metadata:
      labels:
        app: ai-worker
    spec:
      containers:
      - name: ai-worker
        image: 801651112210.dkr.ecr.ap-south-1.amazonaws.com/khushboo-ai-worker:v1 # REAL IMAGE
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-worker-service
spec:
  selector:
    app: ai-worker
  ports:
    - port: 5000
      targetPort: 5000
